CREATE TABLE ATENDENTES
(
ID INT PRIMARY KEY IDENTITY,
USUARIOID INT NOT NULL,
FONE VARCHAR(15) NOT NULL,
CPF CHAR(11) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
RG VARCHAR(15) NOT NULL,
ESTADO INT NOT NULL,
CIDADE VARCHAR(20) NOT NULL,
BAIRRO VARCHAR(20) NOT NULL,
RUA VARCHAR(50) NOT NULL,
NUMERO INT NOT NULL,
SALARIO FLOAT NOT NULL,
COMISSAO FLOAT NOT NULL,
ATIVO BIT NOT NULL,
CONSTRAINT UC_ATENDENTES UNIQUE (CPF, RG),
CONSTRAINT FK_USUARIOS_ATENDENTES FOREIGN KEY (USUARIOID) REFERENCES USUARIOS (ID)
)
SELECT * FROM ATENDENTES
SELECT * FROM USUARIOS

INSERT INTO USUARIOS (NOME, EMAIL, SENHA, FUNCAO) 
VALUES ('Cezar', 'cezar.atendimento@arnold.com', 'Pa55w.rd', 3)

INSERT INTO ATENDENTES (USUARIOID, FONE, CPF, DATA_NASCIMENTO, RG, ESTADO, CIDADE, BAIRRO, RUA, NUMERO, SALARIO, COMISSAO, ATIVO)
VALUES (23, '47 9923-0444', '33619823081', '1989/10/25', '25.814.141-4', 23, 'Blumenau', 'Vila Nova', 'Paraiba', 26, 1500.30, 2, 1)