CREATE TABLE USUARIOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(70) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
SENHA VARCHAR(10) NOT NULL,
FUNCAO INT NOT NULL,
CONSTRAINT UC_USUARIOS UNIQUE (EMAIL)
)
INSERT INTO USUARIOS (NOME, EMAIL, SENHA, FUNCAO) 
VALUES ('Arnold Schwarzenegger', 'arnold@arnoldhealthclub.com', 'Pa55w.rd', 1)
INSERT INTO USUARIOS (NOME, EMAIL, SENHA, FUNCAO) 
VALUES ('Lucas', 'lucas@arnoldhealthclub.com', 'Pa55w.rd', 2)
INSERT INTO USUARIOS (NOME, EMAIL, SENHA, FUNCAO) 
VALUES ('Eduardo', 'eduardo@arnoldhealthclub.com', 'Pa55w.rd', 3)

CREATE TABLE INSTRUTORES
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(70) NOT NULL,
FONE VARCHAR(15) NOT NULL,
CPF CHAR(11) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
RG VARCHAR(15) NOT NULL,
ESTADO INT NOT NULL,
CIDADE VARCHAR(20) NOT NULL,
BAIRRO VARCHAR(20) NOT NULL,
RUA VARCHAR(50) NOT NULL,
NUMERO INT NOT NULL,
SALARIO FLOAT NOT NULL,
COMISSAO FLOAT NOT NULL,
ATIVO BIT NOT NULL,
USUARIO_ID_FK INT NOT NULL REFERENCES USUARIOS
CONSTRAINT UC_INSTRUTORES UNIQUE (CPF, RG)
)
INSERT INTO INSTRUTORES (NOME, FONE, CPF, DATA_NASCIMENTO, RG, ESTADO, CIDADE, BAIRRO, RUA, NUMERO, SALARIO, COMISSAO, ATIVO)
VALUES ('Bruno dos Santos', '47 55555-4444', '12345123451', 'bruno@arnoldhealthclub.com', '06/06/1985', '12345123', 23, 'Blumenau', 'Centro', 'Amadeu da Luz', 456, 1700.54, 10, 1)

CREATE TABLE CLIENTES
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(70) NOT NULL,
CPF CHAR(11) NOT NULL,
RG VARCHAR(15) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
FONE_CELULAR VARCHAR (15) NOT NULL,
FONE_FIXO VARCHAR (15) NULL,
DATA_MATRICULA DATE NOT NULL DEFAULT GETDATE(),
DATA_ADESAO_CONTRATO DATE NOT NULL,
DATA_TERMINO_CONTRATO DATE NOT NULL,
ATIVO BIT NOT NULL,
CONSTRAINT UC_CLIENTES UNIQUE (CPF, RG, EMAIL)
)

CREATE TABLE CATEGORIAS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(30) NOT NULL
)

CREATE TABLE PLANOS
(
ID INT PRIMARY KEY IDENTITY,
CATEGORIA_ID_FK INT NOT NULL,
FOREIGN KEY (CATEGORIA_ID_FK) REFERENCES CATEGORIAS (ID),
QTDD_AULA_SEMANA INT NOT NULL,
VALOR FLOAT NOT NULL,
)


CREATE TABLE MODALIDADES_INSTRUTOR_CLIENTE
(
INSTRUTOR_ID_FK INT NOT NULL,
FOREIGN KEY (INSTRUTOR_ID_FK) REFERENCES INSTRUTORES (ID),
PLANO_ID_FK INT NOT NULL,
FOREIGN KEY (PLANO_ID_FK) REFERENCES PLANOS (ID),
CLIENTE_ID_FK INT NOT NULL,
FOREIGN KEY (CLIENTE_ID_FK) REFERENCES CLIENTES (ID)
)


CREATE TABLE FORMAS_PAGAMENTO
(
ID INT PRIMARY KEY IDENTITY,
DESCRICAO VARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE PRODUTOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(50) NOT NULL,
DESCRICAO VARCHAR(50) NULL,
PRECO_UNITARIO FLOAT NOT NULL,
QTD_ESTOQUE FLOAT NOT NULL
)

CREATE TABLE ENTRADAS_PRODUTO_CX
(
ID INT PRIMARY KEY IDENTITY,
DATA_ENTRADA DATETIME2 NOT NULL DEFAULT GETDATE(),
VALORTOTAL FLOAT NOT NULL,
USUARIO_ID_FK INT NOT NULL REFERENCES USUARIOS
)



CREATE TABLE ITENS_CAIXA_ENTRADA
(
ENTRADA_ID_FK INT NOT NULL REFERENCES ENTRADAS_PRODUTO_CX,
PRODUTO_ID_FK INT NOT NULL REFERENCES PRODUTOS, 
QUANTIDADE FLOAT NOT NULL,
VALOR_UNITARIO FLOAT NOT NULL,
PRIMARY KEY (ENTRADA_ID_FK, PRODUTO_ID_FK)
)

CREATE TABLE VENDAS
(
ID INT PRIMARY KEY IDENTITY,
DATA_SAIDA  DATETIME2 NOT NULL DEFAULT GETDATE(),
VALORTOTAL FLOAT NOT NULL,
USUARIO_ID_FK INT NOT NULL REFERENCES USUARIOS,
CLIENTE_ID_FK INT NOT NULL REFERENCES CLIENTES
)


CREATE TABLE ITENS_VENDA
(
VENDA_ID_FK INT NOT NULL REFERENCES VENDAS,
PRODUTO_ID_FK INT NOT NULL REFERENCES PRODUTOS,
QUANTIDADE FLOAT NOT NULL,
VALOR_UNITARIO FLOAT NOT NULL,
PRIMARY KEY (VENDA_ID_FK, PRODUTO_ID_FK)
)
