SELECT * FROM PLANOS_INSTRUTOR_CLIENTE


SELECT M.NOME AS 'MODALIDADE',
       P.QTDD_AULA_SEMANA AS 'QTD AULA SEMANA',
       P.QTDD_MES AS 'DURAÇÂO',
       P.VALOR AS 'PREÇO'
  FROM CATEGORIAS M 
  JOIN PLANOS P
    ON M.ID = P.CATEGORIAID 

SELECT PIC.ID IDPIC,
       PIC.INSTRUTORID IDInstrutor,
       USUARIO.NOME,
       PIC.PLANOID IDPlano,
       PIC.CLIENTEID IDCliente,
       CLIENTE.NOME,
       PIC.FORMA_PAGAMENTOID IDFormapagamento,
       FORMA_PAGAMENTO.DESCRICAO FormaPagamento,
       C.NOME MODALIDADE,
       PLANO.QTDD_AULA_SEMANA QtdAulaSemana,
       PLANO.QTDD_MES QtdMesesDuracao,
       PLANO.VALOR,
       PIC.DATA_ADESAO_CONTRATO AdesaoContrato,
       PIC.DATA_TERMINO_CONTRATO TerminoContrato
   FROM PLANOS_INSTRUTOR_CLIENTE PIC
   JOIN PLANOS PLANO
     ON PLANO.ID = PIC.PLANOID
   JOIN CATEGORIAS C 
     ON C.ID = PLANO.CATEGORIAID
   JOIN INSTRUTORES INSTRUTOR
     ON INSTRUTOR.ID = PIC.INSTRUTORID
   JOIN USUARIOS USUARIO
     ON USUARIO.ID = INSTRUTOR.USUARIOID
   JOIN CLIENTES CLIENTE
     ON CLIENTE.ID = PIC.CLIENTEID
   JOIN FORMAS_PAGAMENTO FORMA_PAGAMENTO
     ON FORMA_PAGAMENTO.ID = PIC.FORMA_PAGAMENTOID


  SELECT PIC.ID IDPIC,
       PIC.INSTRUTORID IDInstrutor,
       USUARIO.NOME Instrutor,
       PIC.PLANOID IDPlano,
       PIC.CLIENTEID IDCliente,
       CLIENTE.NOME Nome,
       PIC.FORMA_PAGAMENTOID IDFormapagamento,
       FORMA_PAGAMENTO.DESCRICAO FormaPagamento,
       C.NOME Modalidade,
       PLANO.QTDD_AULA_SEMANA QtdAulaSemana,
       PLANO.QTDD_MES QtdMesesDuracao,
       PLANO.VALOR Valor,
       PIC.DATA_ADESAO_CONTRATO AdesaoContrato,
       PIC.DATA_TERMINO_CONTRATO TerminoContrato
   FROM PLANOS_INSTRUTOR_CLIENTE PIC
   JOIN PLANOS PLANO
     ON PLANO.ID = PIC.PLANOID
   JOIN CATEGORIAS C 
     ON C.ID = PLANO.CATEGORIAID
   JOIN INSTRUTORES INSTRUTOR
     ON INSTRUTOR.ID = PIC.INSTRUTORID
   JOIN USUARIOS USUARIO
     ON USUARIO.ID = INSTRUTOR.USUARIOID
   JOIN CLIENTES CLIENTE
     ON CLIENTE.ID = PIC.CLIENTEID
   JOIN FORMAS_PAGAMENTO FORMA_PAGAMENTO
     ON FORMA_PAGAMENTO.ID = PIC.FORMA_PAGAMENTOID
  WHERE INSTRUTOR.ID = 2

  INSERT INTO PLANOS_INSTRUTOR_CLIENTE (INSTRUTORID, PLANOID, CLIENTEID, FORMA_PAGAMENTOID, DATA_ADESAO_CONTRATO,
              DATA_TERMINO_CONTRATO)
       VALUES (2, 4, 1, 2, '2021/02/15', '2021/08/15')